# Site settings
title: Diary
email: lou920217@gmail.com
description: Diary, just some summaries, some notes.
baseurl: "/" 
url: "http://lou920217.github.io"
owner: "xiaohui"
permalink: /Diary/:categories/:title.html
paginate: 10,
paginate_path: "/Diary/page:num"

# deploy path
path: /Diary/
evn: 'production'

# Social account
github: lou920217

#avatar and Favicon
avatar: /assets/images/avatar.jpg
favicon: /assets/images/avatar.jpg

# Build settings
markdown: kramdown

# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
