# Site settings
title: Diary
email: lou920217@gmail.com
description: Diary, just some summaries, some notes.
baseurl: "" 
url: "http://lou920217.github.io/Diary/"
owner: "xiaohui"
permalink: /:categories/:title.html
paginate: 2,
paginate_path: "page:num"

# Social account
github: lou920217

#avatar and Favicon
avatar: /assets/images/avatar.jpg
favicon: /assets/images/avatar.jpg

# Build settings
markdown: kramdown

# Jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
